In [1]:
# Assingnment for Numpy and pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Creating a dataframe

# using month as the column of the dataFrame

Month = ['January','Feburary','March','April','May','June','July','August','September','October','November','December']

# Days as the index of the data frame
Days = np.arange(1,31)

Readings = np.random.randint(2500,1000000,360).reshape(30,12)

Temp = pd.DataFrame(data = Readings ,index = Days, columns = Month)
Temp

,January,Feburary,March,April,May,June,July,August,September,October,November,December
1,786553,464854,894962,212802,681797,614218,170607,198871,763056,684304,317458,897797
2,711176,538220,43911,917998,974575,614915,208722,94179,504855,870551,591787,67639
3,546263,262041,489864,463797,918983,944612,463979,763935,463343,222376,358934,21135
4,486655,893091,173706,903270,489551,633824,466450,141390,497839,102920,978374,482769
5,559171,555421,272924,5532,828029,626914,198884,988468,598935,800829,4702,898320
6,208689,561033,495452,433993,678051,27387,66043,244361,329264,882363,286862,549554
7,4221,19599,61607,164073,297030,438930,623752,373669,818134,675638,120549,805506
8,230332,229176,436153,885191,642229,107503,318595,337800,150708,297800,121878,653098
9,154159,576887,562649,219014,927425,157142,24278,503590,786490,14765,505756,767804
10,509465,55089,81776,38860,457431,463022,111570,399572,591500,120000,939580,13712
11,380728,435694,487228,761580,759308,32334,602828,922322,14779,482958,208599,640855
12,163797,72175,6493,756389,454353,672262,392546,168094,103709,934106,291685,939832
13,237556,159665,406613,978825,883974,771900,951273,360003,814320,685762,821622,933227
14,719054,615024,118595,590876,495290,696669,853038,337768,605741,108658,574276,637833
15,521128,289842,535145,399297,572639,326566,889558,542956,456444,635421,127635,222937
16,584243,508758,788480,943225,732804,698189,987655,154745,80631,880354,579857,778054
17,715864,251958,683981,505804,290995,730886,191760,17376,632839,569228,798398,992802
18,201284,825261,755001,439467,496846,969560,114177,182517,144036,522125,187269,776697
19,746598,722340,792225,842785,522538,196139,889029,966164,855444,241707,102015,43441
20,312067,885752,347371,831875,351109,208199,220861,64594,842461,856036,158097,938074
21,882750,737827,941171,151084,296222,824701,46301,922885,965971,592390,103859,863501
22,322476,9052,860725,572681,606312,573550,48090,562993,833195,932293,130282,789929
23,244158,49273,608670,788251,741934,897266,406992,328956,831076,58678,458589,335740
24,827248,942496,131526,665019,583080,729283,926510,960477,516454,615708,352233,256863
25,295383,738596,673602,864968,223794,592168,380818,235323,907070,517708,462341,698310
26,491507,845998,360837,154115,882526,443192,163932,67342,628411,385976,547050,832898
27,269566,33389,772956,921746,928984,800394,664534,134691,233389,179782,198519,304746
28,797801,193522,517205,695473,15444,264363,758277,539944,749399,567351,976006,830499
29,544985,95531,729450,337051,807937,783723,486088,858501,879822,78252,284928,592346
30,888314,593365,589003,624804,655924,181019,365864,486942,276081,301293,932922,286790

In [5]:
 # finding Maximun sale of March, April,September
    
    
Temp[['March','April','September']].max()

March        941171
April        978825
September    965971
dtype: int32

In [6]:
 # finding Minimun sale of March, April,September
    
    
Temp[['March','April','September']].min()

March         6493
April         5532
September    14779
dtype: int32

In [24]:
#  Finding the 20th and 75th percentile of all months

Temp.quantile([0.20 , 0.75])

,January,Feburary,March,April,May,June,July,August,September,October,November,December,Sum
0.20,236111.2,90859.8,165270.00,217771.6,433704.20,205787.00,153981.0,152074.00,267542.6,167825.6,129752.60,280804.60,5394148.60
0.75,714692.0,695511.0,718082.75,840057.5,795779.75,730485.25,654338.5,557983.75,817180.5,685397.5,578461.75,832298.25,6562214.25

In [35]:
# Creating a new column to hold the sum of sales for each month

Temp['Total'] = Temp.sum(axis = 1)
Temp

,January,Feburary,March,April,May,June,July,August,September,October,November,December,Sum,Total
1,786553.000000,464854.000000,894962.000000,212802.000000,681797.000000,614218.000000,170607.000000,198871.000000,763056.0,684304.000000,317458.000000,897797.000000,40123674.0,4.681095e+07
2,711176.000000,538220.000000,43911.000000,917998.000000,974575.000000,614915.000000,208722.000000,94179.000000,504855.0,870551.000000,591787.000000,67639.000000,36831168.0,4.296970e+07
3,546263.000000,262041.000000,489864.000000,463797.000000,918983.000000,944612.000000,463979.000000,763935.000000,463343.0,222376.000000,358934.000000,21135.000000,35515572.0,4.143483e+07
4,486655.000000,893091.000000,173706.000000,903270.000000,489551.000000,633824.000000,466450.000000,141390.000000,497839.0,102920.000000,978374.000000,482769.000000,37499034.0,4.374887e+07
5,559171.000000,555421.000000,272924.000000,5532.000000,828029.000000,626914.000000,198884.000000,988468.000000,598935.0,800829.000000,4702.000000,898320.000000,38028774.0,4.436690e+07
6,208689.000000,561033.000000,495452.000000,433993.000000,678051.000000,27387.000000,66043.000000,244361.000000,329264.0,882363.000000,286862.000000,549554.000000,28578312.0,3.334136e+07
7,4221.000000,19599.000000,61607.000000,164073.000000,297030.000000,438930.000000,623752.000000,373669.000000,818134.0,675638.000000,120549.000000,805506.000000,26416248.0,3.081896e+07
8,230332.000000,229176.000000,436153.000000,885191.000000,642229.000000,107503.000000,318595.000000,337800.000000,150708.0,297800.000000,121878.000000,653098.000000,26462778.0,3.087324e+07
9,154159.000000,576887.000000,562649.000000,219014.000000,927425.000000,157142.000000,24278.000000,503590.000000,786490.0,14765.000000,505756.000000,767804.000000,31199754.0,3.639971e+07
10,509465.000000,55089.000000,81776.000000,38860.000000,457431.000000,463022.000000,111570.000000,399572.000000,591500.0,120000.000000,939580.000000,13712.000000,22689462.0,2.647104e+07
11,380728.000000,435694.000000,487228.000000,761580.000000,759308.000000,32334.000000,602828.000000,922322.000000,14779.0,482958.000000,208599.000000,640855.000000,34375278.0,4.010449e+07
12,163797.000000,72175.000000,6493.000000,756389.000000,454353.000000,672262.000000,392546.000000,168094.000000,103709.0,934106.000000,291685.000000,939832.000000,29732646.0,3.468809e+07
13,237556.000000,159665.000000,406613.000000,978825.000000,883974.000000,771900.000000,951273.000000,360003.000000,814320.0,685762.000000,821622.000000,933227.000000,48028440.0,5.603318e+07
14,719054.000000,615024.000000,118595.000000,590876.000000,495290.000000,696669.000000,853038.000000,337768.000000,605741.0,108658.000000,574276.000000,637833.000000,38116932.0,4.446975e+07
15,521128.000000,289842.000000,535145.000000,399297.000000,572639.000000,326566.000000,889558.000000,542956.000000,456444.0,635421.000000,127635.000000,222937.000000,33117408.0,3.863698e+07
16,584243.000000,508758.000000,788480.000000,943225.000000,732804.000000,698189.000000,987655.000000,154745.000000,80631.0,880354.000000,579857.000000,778054.000000,46301970.0,5.401896e+07
17,715864.000000,251958.000000,683981.000000,505804.000000,290995.000000,730886.000000,191760.000000,17376.000000,632839.0,569228.000000,798398.000000,992802.000000,38291346.0,4.467324e+07
18,201284.000000,825261.000000,755001.000000,439467.000000,496846.000000,969560.000000,114177.000000,182517.000000,144036.0,522125.000000,187269.000000,776697.000000,33685440.0,3.929968e+07
19,746598.000000,722340.000000,792225.000000,842785.000000,522538.000000,196139.000000,889029.000000,966164.000000,855444.0,241707.000000,102015.000000,43441.000000,41522550.0,4.844298e+07
20,312067.000000,885752.000000,347371.000000,831875.000000,351109.000000,208199.000000,220861.000000,64594.000000,842461.0,856036.000000,158097.000000,938074.000000,36098976.0,4.211547e+07
21,882750.000000,737827.000000,941171.000000,151084.000000,296222.000000,824701.000000,46301.000000,922885.000000,965971.0,592390.000000,103859.000000,863501.000000,43971972.0,5.130063e+07
22,322476.000000,9052.000000,860725.000000,572681.000000,606312.000000,573550.000000,48090.000000,562993.000000,833195.0,932293.000000,130282.000000,789929.000000,37449468.0,4.369105e+07
23,244158.000000,49273.000000,608670.000000,788251.000000,741934.000000,897266.000000,406992.000000,328956.000000,831076.0,58678.000000,458589.000000,335740.000000,34497498.0,4.024708e+07
24,827248.000000,942496.000000,131526.000000,665019.000000,583080.000000,729283.000000,926510.000000,960477.000000,516454.0,615708.000000,352233.000000,256863.000000,45041382.0,5.254828e+07
25,295383.000000,738596.000000,673602.000000,864968.000000,223794.000000,592168.000000,380818.000000,235323.000000,907070.0,517708.000000,462341.000000,698310.000000,39540486.0,4.613057e+07
26,491507.000000,845998.000000,360837.000000,154115.000000,882526.000000,443192.000000,163932.000000,67342.000000,628411.0,385976.000000,547050.000000,832898.000000,34822704.0,4.062649e+07
27,269566.000000,33389.000000,772956.000000,921746.000000,928984.000000,800394.000000,664534.000000,134691.000000,233389.0,179782.000000,198519.000000,304746.000000,32656176.0,3.809887e+07
28,797801.000000,193522.000000,517205.000000,695473.000000,15444.000000,264363.000000,758277.000000,539944.000000,749399.0,567351.000000,976006.000000,830499.000000,41431704.0,4.833699e+07
29,544985.000000,95531.000000,729450.000000,337051.000000,807937.000000,783723.000000,486088.000000,858501.000000,879822.0,78252.000000,284928.000000,592346.000000,38871684.0,4.535030e+07
30,888314.000000,593365.000000,589003.000000,624804.000000,655924.000000,181019.000000,365864.000000,486942.000000,276081.0,301293.000000,932922.000000,286790.000000,37093926.0,4.327625e+07
AVG,478106.366667,438697.633333,487309.366667,568994.833333,606570.466667,534027.666667,433100.366667,428680.933333,562513.2,493911.066667,417402.066667,595090.266667,36266425.4,4.231083e+07

In [33]:
# Creating a new row to hold the avarage sale of each month

Temp.loc['AVG'] = Temp.mean(axis = 0)
Temp

,January,Feburary,March,April,May,June,July,August,September,October,November,December,Sum
1,786553.000000,464854.000000,894962.000000,212802.000000,681797.000000,614218.000000,170607.000000,198871.000000,763056.0,684304.000000,317458.000000,897797.000000,40123674.0
2,711176.000000,538220.000000,43911.000000,917998.000000,974575.000000,614915.000000,208722.000000,94179.000000,504855.0,870551.000000,591787.000000,67639.000000,36831168.0
3,546263.000000,262041.000000,489864.000000,463797.000000,918983.000000,944612.000000,463979.000000,763935.000000,463343.0,222376.000000,358934.000000,21135.000000,35515572.0
4,486655.000000,893091.000000,173706.000000,903270.000000,489551.000000,633824.000000,466450.000000,141390.000000,497839.0,102920.000000,978374.000000,482769.000000,37499034.0
5,559171.000000,555421.000000,272924.000000,5532.000000,828029.000000,626914.000000,198884.000000,988468.000000,598935.0,800829.000000,4702.000000,898320.000000,38028774.0
6,208689.000000,561033.000000,495452.000000,433993.000000,678051.000000,27387.000000,66043.000000,244361.000000,329264.0,882363.000000,286862.000000,549554.000000,28578312.0
7,4221.000000,19599.000000,61607.000000,164073.000000,297030.000000,438930.000000,623752.000000,373669.000000,818134.0,675638.000000,120549.000000,805506.000000,26416248.0
8,230332.000000,229176.000000,436153.000000,885191.000000,642229.000000,107503.000000,318595.000000,337800.000000,150708.0,297800.000000,121878.000000,653098.000000,26462778.0
9,154159.000000,576887.000000,562649.000000,219014.000000,927425.000000,157142.000000,24278.000000,503590.000000,786490.0,14765.000000,505756.000000,767804.000000,31199754.0
10,509465.000000,55089.000000,81776.000000,38860.000000,457431.000000,463022.000000,111570.000000,399572.000000,591500.0,120000.000000,939580.000000,13712.000000,22689462.0
11,380728.000000,435694.000000,487228.000000,761580.000000,759308.000000,32334.000000,602828.000000,922322.000000,14779.0,482958.000000,208599.000000,640855.000000,34375278.0
12,163797.000000,72175.000000,6493.000000,756389.000000,454353.000000,672262.000000,392546.000000,168094.000000,103709.0,934106.000000,291685.000000,939832.000000,29732646.0
13,237556.000000,159665.000000,406613.000000,978825.000000,883974.000000,771900.000000,951273.000000,360003.000000,814320.0,685762.000000,821622.000000,933227.000000,48028440.0
14,719054.000000,615024.000000,118595.000000,590876.000000,495290.000000,696669.000000,853038.000000,337768.000000,605741.0,108658.000000,574276.000000,637833.000000,38116932.0
15,521128.000000,289842.000000,535145.000000,399297.000000,572639.000000,326566.000000,889558.000000,542956.000000,456444.0,635421.000000,127635.000000,222937.000000,33117408.0
16,584243.000000,508758.000000,788480.000000,943225.000000,732804.000000,698189.000000,987655.000000,154745.000000,80631.0,880354.000000,579857.000000,778054.000000,46301970.0
17,715864.000000,251958.000000,683981.000000,505804.000000,290995.000000,730886.000000,191760.000000,17376.000000,632839.0,569228.000000,798398.000000,992802.000000,38291346.0
18,201284.000000,825261.000000,755001.000000,439467.000000,496846.000000,969560.000000,114177.000000,182517.000000,144036.0,522125.000000,187269.000000,776697.000000,33685440.0
19,746598.000000,722340.000000,792225.000000,842785.000000,522538.000000,196139.000000,889029.000000,966164.000000,855444.0,241707.000000,102015.000000,43441.000000,41522550.0
20,312067.000000,885752.000000,347371.000000,831875.000000,351109.000000,208199.000000,220861.000000,64594.000000,842461.0,856036.000000,158097.000000,938074.000000,36098976.0
21,882750.000000,737827.000000,941171.000000,151084.000000,296222.000000,824701.000000,46301.000000,922885.000000,965971.0,592390.000000,103859.000000,863501.000000,43971972.0
22,322476.000000,9052.000000,860725.000000,572681.000000,606312.000000,573550.000000,48090.000000,562993.000000,833195.0,932293.000000,130282.000000,789929.000000,37449468.0
23,244158.000000,49273.000000,608670.000000,788251.000000,741934.000000,897266.000000,406992.000000,328956.000000,831076.0,58678.000000,458589.000000,335740.000000,34497498.0
24,827248.000000,942496.000000,131526.000000,665019.000000,583080.000000,729283.000000,926510.000000,960477.000000,516454.0,615708.000000,352233.000000,256863.000000,45041382.0
25,295383.000000,738596.000000,673602.000000,864968.000000,223794.000000,592168.000000,380818.000000,235323.000000,907070.0,517708.000000,462341.000000,698310.000000,39540486.0
26,491507.000000,845998.000000,360837.000000,154115.000000,882526.000000,443192.000000,163932.000000,67342.000000,628411.0,385976.000000,547050.000000,832898.000000,34822704.0
27,269566.000000,33389.000000,772956.000000,921746.000000,928984.000000,800394.000000,664534.000000,134691.000000,233389.0,179782.000000,198519.000000,304746.000000,32656176.0
28,797801.000000,193522.000000,517205.000000,695473.000000,15444.000000,264363.000000,758277.000000,539944.000000,749399.0,567351.000000,976006.000000,830499.000000,41431704.0
29,544985.000000,95531.000000,729450.000000,337051.000000,807937.000000,783723.000000,486088.000000,858501.000000,879822.0,78252.000000,284928.000000,592346.000000,38871684.0
30,888314.000000,593365.000000,589003.000000,624804.000000,655924.000000,181019.000000,365864.000000,486942.000000,276081.0,301293.000000,932922.000000,286790.000000,37093926.0
AVG,478106.366667,438697.633333,487309.366667,568994.833333,606570.466667,534027.666667,433100.366667,428680.933333,562513.2,493911.066667,417402.066667,595090.266667,36266425.4

In [34]:
Temp

,January,Feburary,March,April,May,June,July,August,September,October,November,December,Sum
1,786553.000000,464854.000000,894962.000000,212802.000000,681797.000000,614218.000000,170607.000000,198871.000000,763056.0,684304.000000,317458.000000,897797.000000,40123674.0
2,711176.000000,538220.000000,43911.000000,917998.000000,974575.000000,614915.000000,208722.000000,94179.000000,504855.0,870551.000000,591787.000000,67639.000000,36831168.0
3,546263.000000,262041.000000,489864.000000,463797.000000,918983.000000,944612.000000,463979.000000,763935.000000,463343.0,222376.000000,358934.000000,21135.000000,35515572.0
4,486655.000000,893091.000000,173706.000000,903270.000000,489551.000000,633824.000000,466450.000000,141390.000000,497839.0,102920.000000,978374.000000,482769.000000,37499034.0
5,559171.000000,555421.000000,272924.000000,5532.000000,828029.000000,626914.000000,198884.000000,988468.000000,598935.0,800829.000000,4702.000000,898320.000000,38028774.0
6,208689.000000,561033.000000,495452.000000,433993.000000,678051.000000,27387.000000,66043.000000,244361.000000,329264.0,882363.000000,286862.000000,549554.000000,28578312.0
7,4221.000000,19599.000000,61607.000000,164073.000000,297030.000000,438930.000000,623752.000000,373669.000000,818134.0,675638.000000,120549.000000,805506.000000,26416248.0
8,230332.000000,229176.000000,436153.000000,885191.000000,642229.000000,107503.000000,318595.000000,337800.000000,150708.0,297800.000000,121878.000000,653098.000000,26462778.0
9,154159.000000,576887.000000,562649.000000,219014.000000,927425.000000,157142.000000,24278.000000,503590.000000,786490.0,14765.000000,505756.000000,767804.000000,31199754.0
10,509465.000000,55089.000000,81776.000000,38860.000000,457431.000000,463022.000000,111570.000000,399572.000000,591500.0,120000.000000,939580.000000,13712.000000,22689462.0
11,380728.000000,435694.000000,487228.000000,761580.000000,759308.000000,32334.000000,602828.000000,922322.000000,14779.0,482958.000000,208599.000000,640855.000000,34375278.0
12,163797.000000,72175.000000,6493.000000,756389.000000,454353.000000,672262.000000,392546.000000,168094.000000,103709.0,934106.000000,291685.000000,939832.000000,29732646.0
13,237556.000000,159665.000000,406613.000000,978825.000000,883974.000000,771900.000000,951273.000000,360003.000000,814320.0,685762.000000,821622.000000,933227.000000,48028440.0
14,719054.000000,615024.000000,118595.000000,590876.000000,495290.000000,696669.000000,853038.000000,337768.000000,605741.0,108658.000000,574276.000000,637833.000000,38116932.0
15,521128.000000,289842.000000,535145.000000,399297.000000,572639.000000,326566.000000,889558.000000,542956.000000,456444.0,635421.000000,127635.000000,222937.000000,33117408.0
16,584243.000000,508758.000000,788480.000000,943225.000000,732804.000000,698189.000000,987655.000000,154745.000000,80631.0,880354.000000,579857.000000,778054.000000,46301970.0
17,715864.000000,251958.000000,683981.000000,505804.000000,290995.000000,730886.000000,191760.000000,17376.000000,632839.0,569228.000000,798398.000000,992802.000000,38291346.0
18,201284.000000,825261.000000,755001.000000,439467.000000,496846.000000,969560.000000,114177.000000,182517.000000,144036.0,522125.000000,187269.000000,776697.000000,33685440.0
19,746598.000000,722340.000000,792225.000000,842785.000000,522538.000000,196139.000000,889029.000000,966164.000000,855444.0,241707.000000,102015.000000,43441.000000,41522550.0
20,312067.000000,885752.000000,347371.000000,831875.000000,351109.000000,208199.000000,220861.000000,64594.000000,842461.0,856036.000000,158097.000000,938074.000000,36098976.0
21,882750.000000,737827.000000,941171.000000,151084.000000,296222.000000,824701.000000,46301.000000,922885.000000,965971.0,592390.000000,103859.000000,863501.000000,43971972.0
22,322476.000000,9052.000000,860725.000000,572681.000000,606312.000000,573550.000000,48090.000000,562993.000000,833195.0,932293.000000,130282.000000,789929.000000,37449468.0
23,244158.000000,49273.000000,608670.000000,788251.000000,741934.000000,897266.000000,406992.000000,328956.000000,831076.0,58678.000000,458589.000000,335740.000000,34497498.0
24,827248.000000,942496.000000,131526.000000,665019.000000,583080.000000,729283.000000,926510.000000,960477.000000,516454.0,615708.000000,352233.000000,256863.000000,45041382.0
25,295383.000000,738596.000000,673602.000000,864968.000000,223794.000000,592168.000000,380818.000000,235323.000000,907070.0,517708.000000,462341.000000,698310.000000,39540486.0
26,491507.000000,845998.000000,360837.000000,154115.000000,882526.000000,443192.000000,163932.000000,67342.000000,628411.0,385976.000000,547050.000000,832898.000000,34822704.0
27,269566.000000,33389.000000,772956.000000,921746.000000,928984.000000,800394.000000,664534.000000,134691.000000,233389.0,179782.000000,198519.000000,304746.000000,32656176.0
28,797801.000000,193522.000000,517205.000000,695473.000000,15444.000000,264363.000000,758277.000000,539944.000000,749399.0,567351.000000,976006.000000,830499.000000,41431704.0
29,544985.000000,95531.000000,729450.000000,337051.000000,807937.000000,783723.000000,486088.000000,858501.000000,879822.0,78252.000000,284928.000000,592346.000000,38871684.0
30,888314.000000,593365.000000,589003.000000,624804.000000,655924.000000,181019.000000,365864.000000,486942.000000,276081.0,301293.000000,932922.000000,286790.000000,37093926.0
AVG,478106.366667,438697.633333,487309.366667,568994.833333,606570.466667,534027.666667,433100.366667,428680.933333,562513.2,493911.066667,417402.066667,595090.266667,36266425.4